apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: redis
  labels:
    app: redis
spec:
  clusterIP: None  # Headless Service
  ports:
  - port: 6379
    name: server
  selector:
    app: redis
