kind: Service
apiVersion: v1
metadata:
  name: mysql-source-headless
  labels:
    app: mysql-source
spec:
  ports:
    - name: tcp-3306
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql-source
  clusterIP: None
  type: ClusterIP
