apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: nacos
  labels:
    app: nacos
spec:
  clusterIP: None  # Headless Service
  ports:
  - port: 28848
    name: server
  - port: 27848
    name: raft
  selector:
    app: nacos
