apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
  namespace: nacos
data:
  application.properties: |
    # 应用端口
    server.port=28848
    PREFER_HOST_MODE=ip

    # 数据库配置
    spring.datasource.platform=mysql
    db.num=1
    db.url.0=jdbc:mysql://mysql-source-headless.mysql.svc.cluster.local:3306/flash_im?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    db.user=root
    db.password=Opsszr2025!

    # 鉴权配置
    nacos.core.auth.enabled=true
    nacos.core.auth.server.identity.key=k8s_nacos
    nacos.core.auth.server.identity.value=k8s_nacos
    nacos.core.auth.plugin.nacos.token.secret.key=k8sNacosSecretKey01234567890123456789012345678901
