kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins
  namespace: jenkins-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccount: jenkins-k8s-sa
      nodeSelector: 
        cname: jenkins
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.514-jdk17
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        - containerPort: 50000
          name: agent
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        volumeMounts:
        - name: jenkins-volume
          subPath: jenkins-home
          mountPath: /var/jenkins_home
        - name: host-docker-sock
          mountPath: /var/run/docker.sock
        - name: host-docker-bin
          mountPath: /usr/bin/docker
        - name: host-docker-daemon
          mountPath: /etc/docker/daemon.json
      volumes:
      - name: jenkins-volume
        persistentVolumeClaim:
          claimName: jenkins-k8s-pvc
      - name: host-docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: host-docker-bin
        hostPath:
          path: /usr/bin/docker
      - name: host-docker-daemon
        hostPath:
          path: /etc/docker/daemon.json
