spring:
  cloud:
    # Nacos 服务发现与注册配置
    nacos:
      discovery:
        server-addr: nacos-0.nacos-headless.nacos.svc.cluster.local:28848,nacos-1.nacos-headless.nacos.svc.cluster.local:28848 # nacos集群使用','隔开
        username: 'nacos'
        password: 'nacos'
        namespace: ${spring.profiles.active}
      config:
        server-addr: nacos-0.nacos-headless.nacos.svc.cluster.local:28848,nacos-1.nacos-headless.nacos.svc.cluster.local:28848 # nacos集群使用','隔开
        username: 'nacos'
        password: 'nacos'
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:flash-im-auth.yaml

  # mysql连接配置
  datasource:
    url: jdbc:mysql://mysql-source-headless.mysql.svc.cluster.local:3306/flash_im?allowMultiQueries=true&characterEncoding=utf8&connectTimeout=3000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Opsszr2025!
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    # Redis配置
    redis:
      host: redis-0.redis-headless.redis.svc.cluster.local
      port: 6379
      password: 123456

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志


flashim:
  jwt:
    enabled: true
    privateKeyPath: classpath:rsa/jwt_private.pem
    publicKeyPath: classpath:rsa/jwt_public.pem
    accessTokenExpiration: 1800000    # 30分钟
    refreshTokenExpiration: 2592000000 # 30天
    refreshThreshold: 300000      # 5分钟